### ISSUE TITLE
Complete User requirements of Use Cases for Turkish Consortium

### ISSUE THREAD

**Issue by annemonceaux** [ModelWriter/WP1#14]

**Comment by ferhaterata** [comment]
Hi @m-challenger 

Could you remind Turkish partners regarding final updates with a separate email?

Thanks

/cc @ModelWriter/turkish-consortium

**Comment by ferhaterata** [comment]
Dear @ersangurdogan and @eraytuzun (/cc @mengusoglu)

Could you please insert the user requirements of your use cases into [Requirement Repository](https://github.com/ModelWriter/Requirements/labels/User%20Requirements%20Document%20%28URD%29) as soon as possible?

If you have problem entering your reqs, you can email us to do on your behalf?
